version: "3.9"

services:
    db:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        env_file:
            - .env
    web:
        build: .
        command: sh -c "python manage.py migrate --no-input && python /code/manage.py runserver 0.0.0.0:${APP_PORT}"
        ports:
            - "${APP_PORT}:8000"
        volumes:
            - .:/code
        depends_on:
            - db
        env_file:
            - .env
        environment:
            WAIT_HOSTS: db:${POSTGRES_PORT}
volumes:
    postgres_data:
        name: ${POSTGRES_VOLUME}